// <auto-generated />
using MVCOne.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCOne.Migrations
{
    [DbContext(typeof(MVCOneContext))]
    [Migration("20190128213616_PhoneFormat")]
    partial class PhoneFormat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCOne.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Association");

                    b.Property<string>("Category");

                    b.Property<string>("City");

                    b.Property<string>("CoName");

                    b.Property<string>("Country");

                    b.Property<string>("County");

                    b.Property<string>("Distrikt");

                    b.Property<string>("EMail");

                    b.Property<string>("ExaminationLevel");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("Nationality");

                    b.Property<long>("Phone1");

                    b.Property<long>("Phone2");

                    b.Property<string>("RefCategoryType");

                    b.Property<string>("RefNumber");

                    b.Property<string>("RefType");

                    b.Property<long>("Ssn");

                    b.Property<string>("StreetAddress");

                    b.Property<string>("ZIPCode");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
